//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminForm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class adatbazis : DbContext
    {
        public adatbazis()
            : base("name=adatbazis")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<felhasznalo> felhasznalo { get; set; }
        public virtual DbSet<newsletter> newsletter { get; set; }
        public virtual DbSet<playlists> playlists { get; set; }
        public virtual DbSet<songs> songs { get; set; }
        public virtual DbSet<likes> likes { get; set; }
    }
}
