//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class felhasznalo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public felhasznalo()
        {
            this.playlists = new HashSet<playlists>();
        }
    
        public int id { get; set; }
        public string felhnev { get; set; }
        public string jelszo { get; set; }
        public string email { get; set; }
        public string profile_image { get; set; }
        public System.DateTime time { get; set; }
        public string bio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<playlists> playlists { get; set; }
    }
}
